import { pgTable, text, serial, integer, timestamp } from "drizzle-orm/pg-core";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod/v4";

export const charactersTable = pgTable("characters", {
  id: serial("id").primaryKey(),
  userId: text("user_id"),
  name: text("name").notNull(),
  level: integer("level").notNull().default(1),
  experience: integer("experience").notNull().default(0),
  origin: text("origin").notNull(),
  clanHeritage: text("clan_heritage"),
  specialization: text("specialization").notNull(),
  grade: text("grade").notNull().default("4° Grau"),
  backstory: text("backstory"),
  personality: text("personality"),
  technique: text("technique"),
  techniqueDescription: text("technique_description"),
  strength: integer("strength").notNull().default(1),
  dexterity: integer("dexterity").notNull().default(1),
  constitution: integer("constitution").notNull().default(1),
  intelligence: integer("intelligence").notNull().default(1),
  wisdom: integer("wisdom").notNull().default(1),
  charisma: integer("charisma").notNull().default(1),
  hp: integer("hp").notNull().default(10),
  maxHp: integer("max_hp").notNull().default(10),
  energy: integer("energy").notNull().default(10),
  maxEnergy: integer("max_energy").notNull().default(10),
  armorClass: integer("armor_class").notNull().default(10),
  masteryBonus: integer("mastery_bonus").notNull().default(2),
  skills: text("skills"),
  equipment: text("equipment"),
  aptitudes: text("aptitudes"),
  abilities: text("abilities"),
  customStats: text("custom_stats"),
  notes: text("notes"),
  photoUrl: text("photo_url"),
  age: text("age"),
  height: text("height"),
  weight: text("weight"),
  school: text("school"),
  occupation: text("occupation"),
  appearance: text("appearance"),
  ideals: text("ideals"),
  bonds: text("bonds"),
  complications: text("complications"),
  innateDomain: text("innate_domain"),
  soulIntegrity: integer("soul_integrity").notNull().default(10),
  maxSoulIntegrity: integer("max_soul_integrity").notNull().default(10),
  attention: integer("attention").notNull().default(10),
  movement: text("movement").notNull().default("9m"),
  hitDice: text("hit_dice").notNull().default("1d8"),
  resistances: text("resistances"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow().$onUpdate(() => new Date()),
});

export const insertCharacterSchema = createInsertSchema(charactersTable).omit({ id: true, userId: true, createdAt: true, updatedAt: true });
export type InsertCharacter = z.infer<typeof insertCharacterSchema>;
export type Character = typeof charactersTable.$inferSelect;
